neutral: [
    office/guide/1,
]

encourage: [
    office/guide/1,
]

attention: [
    office/guide/1,
]

consolation: [
    office/guide/1,
]

greeting: [
    office/guide/1,
]

waiting: [
    office/guide/1,
]

advice: [
    office/guide/1,
]

praise: [
    office/guide/1,
]

command: [
    office/guide/1,
]

user-defined: [
    office/guide/2,
]
