neutral: [
    sm/neutral/1,
    sm/neutral/2,
    sm/neutral/3,
    sm/neutral/4,
]

encourage: [
    sm/encourage/1,
]

attention: [
    sm/attention/1,
    sm/attention/2,
]

consolation: [
    sm/consolation/1,
]

greeting: [
    sm/greeting/1,
    sm/greeting/2,
    sm/open/1,
]

waiting: [
    sm/close/1,
]

advice: [
    sm/pointing/1,
    sm/pointing/2,
]

praise: [
    sm/praise/1
]

command: [
    sm/command/1,
    sm/command/2,
]

user-defined: [
    sm/user/1,
    sm/user/2
]
