neutral: [
    sm/neutral/1,
    sm/neutral/2,
    sm/neutral/3,
    sm/neutral/4,
    sm/neutral/5,
]

encourage: [
    sm/encourage/1,
]

attention: [
    sm/attention/1,
    sm/attention/2,
]

consolation: [
    sm/consolation/1,
]

greeting: [
    sm/greeting/1,
    sm/greeting/2,
    sm/greeting/3,
    sm/greeting/4,
]

waiting: [
    sm/close/1,
    sm/close/2,
]

advice: [
    sm/advice/1,
    sm/advice/2,
]

praise: [
    sm/praise/1
]

command: [
    sm/command/1,
    sm/command/2,
]

user-defined: [
    sm/open/1,
    sm/close/1,
]
